from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Venue',
    'EventSource',
    'Tag',
    'Event',
    'SavedEvent',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'savedEvents': 'SavedEvent',
    },
    'Venue': {
        'events': 'Event',
    },
    'EventSource': {
        'events': 'Event',
    },
    'Tag': {
        'events': 'Event',
    },
    'Event': {
        'venue': 'Venue',
        'source': 'EventSource',
        'tags': 'Tag',
        'savedBy': 'SavedEvent',
    },
    'SavedEvent': {
        'user': 'User',
        'event': 'Event',
    },
}

# fmt: on